name: Publish package to GitHub Packages
on:
  workflow_dispatch:
  # push:
  # release:
    # types: [created]
jobs:
  build:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - name: PrepareReg Names
        run: |
         echo REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
         echo ACTOR=$(echo ${{ github.actor }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
         echo NODE_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }} >> $GITHUB_ENV
      - name: Checkout Files
        uses: actions/checkout@v2
      - name: Update the repository url to match this repo
        run: |
          echo "const fs = require('fs');var pkg=require('./package.json');if(pkg.repository && pkg.repository.url){pkg.repository.url='git://github.com/$REPOSITORY';fs.writeFileSync('./package.json', JSON.stringify(pkg, null, 2) );}" | node -
          cat package.json
      # Setup .npmrc file to publish to GitHub Packages
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@andrewiski'
      - name: NPM CI
        run: npm ci
      - name: NPM Publish
        run: npm publish --registry "https://npm.pkg.github.com/@$ACTOR"
